// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSn1lw7lY8SYgWbiy1UUD-RF8cUphdeis',
    appId: '1:562785053529:web:8fac9ef7e35a937c6fba48',
    messagingSenderId: '562785053529',
    projectId: 'app-mobile2-99d9a',
    authDomain: 'app-mobile2-99d9a.firebaseapp.com',
    storageBucket: 'app-mobile2-99d9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnKzoDciPit-7qSSXWL5dvTUOg93yWC-M',
    appId: '1:562785053529:android:6a138485d32307d26fba48',
    messagingSenderId: '562785053529',
    projectId: 'app-mobile2-99d9a',
    storageBucket: 'app-mobile2-99d9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGk-q9tV_mHsjaF88e5SkRUr_jBIAViSc',
    appId: '1:562785053529:ios:052a1b37bd6bce326fba48',
    messagingSenderId: '562785053529',
    projectId: 'app-mobile2-99d9a',
    storageBucket: 'app-mobile2-99d9a.firebasestorage.app',
    iosBundleId: 'com.example.appMobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGk-q9tV_mHsjaF88e5SkRUr_jBIAViSc',
    appId: '1:562785053529:ios:052a1b37bd6bce326fba48',
    messagingSenderId: '562785053529',
    projectId: 'app-mobile2-99d9a',
    storageBucket: 'app-mobile2-99d9a.firebasestorage.app',
    iosBundleId: 'com.example.appMobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSn1lw7lY8SYgWbiy1UUD-RF8cUphdeis',
    appId: '1:562785053529:web:e37d59751c0192de6fba48',
    messagingSenderId: '562785053529',
    projectId: 'app-mobile2-99d9a',
    authDomain: 'app-mobile2-99d9a.firebaseapp.com',
    storageBucket: 'app-mobile2-99d9a.firebasestorage.app',
  );
}
